import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import ContactBubble from "./_components/ContactBubble";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <div className="md:px-20">
          <Header />
          {children}
        </div>
        <ContactBubble />
        <Footer />
      </body>
    </html>
  );
}
